<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container03AXfbo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container03AXfbo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container03AXfbo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container03AXfbo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container03AXfbo\App_KernelDevDebugContainer([
    'container.build_hash' => '03AXfbo',
    'container.build_id' => '1e5141fc',
    'container.build_time' => 1776686128,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container03AXfbo');
