BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EQUIPMENTS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MAINTENANCE CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/ 

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE EQUIPMENT_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE MAINTENANCE_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE USER_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

CREATE SEQUENCE EQUIPMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MAINTENANCE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE USERS (
    ID NUMBER(10) NOT NULL,
    LAST_NAME VARCHAR2(120) NOT NULL,
    FIRST_NAME VARCHAR2(120) NOT NULL,
    EMAIL VARCHAR2(180) NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    STATUS VARCHAR2(30) NOT NULL,
    ROLE_NAME VARCHAR2(80) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (ID),
    CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE EQUIPMENTS (
    ID NUMBER(10) NOT NULL,
    USER_ID NUMBER(10) NOT NULL,
    NAME VARCHAR2(120) NOT NULL,
    TYPE VARCHAR2(80) NOT NULL,
    STATUS VARCHAR2(30) NOT NULL,
    PURCHASE_DATE DATE,
    CONSTRAINT PK_EQUIPMENTS PRIMARY KEY (ID),
    CONSTRAINT FK_EQUIPMENTS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE MAINTENANCE (
    ID NUMBER(10) NOT NULL,
    USER_ID NUMBER(10) NOT NULL,
    EQUIPMENT_ID NUMBER(10) NOT NULL,
    MAINTENANCE_DATE DATE NOT NULL,
    MAINTENANCE_TYPE VARCHAR2(80) NOT NULL,
    COST NUMBER(10, 2) NOT NULL,
    CONSTRAINT PK_MAINTENANCE PRIMARY KEY (ID),
    CONSTRAINT FK_MAINTENANCE_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENTS(ID),
    CONSTRAINT FK_MAINTENANCE_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
