<?php

namespace Container03AXfbo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0YiO986Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0YiO986' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0YiO986'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'animalService' => ['privates', 'App\\Service\\AnimalManagementService', 'getAnimalManagementServiceService', true],
        ], [
            'animalService' => 'App\\Service\\AnimalManagementService',
        ]);
    }
}
