<?php

namespace Container03AXfbo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3nfaAkZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3nfaAkZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3nfaAkZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'crudService' => ['privates', 'App\\Service\\PdoCrudService', 'getPdoCrudServiceService', true],
            'discordService' => ['privates', 'App\\Service\\DiscordWebhookService', 'getDiscordWebhookServiceService', true],
            'groqService' => ['privates', 'App\\Service\\GroqAIService', 'getGroqAIServiceService', true],
            'weatherService' => ['privates', 'App\\Service\\OpenWeatherService', 'getOpenWeatherServiceService', true],
        ], [
            'crudService' => 'App\\Service\\PdoCrudService',
            'discordService' => 'App\\Service\\DiscordWebhookService',
            'groqService' => 'App\\Service\\GroqAIService',
            'weatherService' => 'App\\Service\\OpenWeatherService',
        ]);
    }
}
