<?php

namespace Container03AXfbo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroqAIServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\GroqAIService' shared autowired service.
     *
     * @return \App\Service\GroqAIService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'GroqAIService.php';

        return $container->privates['App\\Service\\GroqAIService'] = new \App\Service\GroqAIService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('GROQ_API_KEY'));
    }
}
