<?php

namespace Container03AXfbo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOracleSqlPlusCrudServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\OracleSqlPlusCrudService' shared autowired service.
     *
     * @return \App\Service\OracleSqlPlusCrudService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'OracleSqlPlusCrudService.php';

        return $container->privates['App\\Service\\OracleSqlPlusCrudService'] = new \App\Service\OracleSqlPlusCrudService(($container->services['doctrine.dbal.default_connection'] ?? $container->load('getDoctrine_Dbal_DefaultConnectionService')));
    }
}
