parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\MailService:
        arguments:
            $fromEmail: '%env(MAIL_FROM)%'
            $toEmail:   '%env(MAIL_TO)%'

    App\Service\WeatherService:
        arguments:
            $apiKey: '%env(OPENWEATHER_API_KEY)%'        