<?php

namespace Container28xyWKx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B6B3iaxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b6B3iax' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b6B3iax'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'crudService' => ['privates', 'App\\Service\\PdoCrudService', 'getPdoCrudServiceService', true],
        ], [
            'crudService' => 'App\\Service\\PdoCrudService',
        ]);
    }
}
