<?php

namespace Container28xyWKx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Brsfv0zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.brsfv0z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.brsfv0z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'equipment' => ['privates', '.errored..service_locator.brsfv0z.App\\Entity\\Equipment', NULL, 'Cannot autowire service ".service_locator.brsfv0z": it needs an instance of "App\\Entity\\Equipment" but this type has been excluded in "config/services.yaml".'],
        ], [
            'equipment' => 'App\\Entity\\Equipment',
        ]);
    }
}
