<?php

namespace Container28xyWKx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoogleMapsServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\GoogleMapsService' shared autowired service.
     *
     * @return \App\Service\GoogleMapsService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'GoogleMapsService.php';

        return $container->privates['App\\Service\\GoogleMapsService'] = new \App\Service\GoogleMapsService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('GOOGLE_MAPS_API_KEY'));
    }
}
