<?php

namespace Container28xyWKx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getManagementAccessSmokeCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ManagementAccessSmokeCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.App\\Command\\ManagementAccessSmokeCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:management-access-smoke', [], 'Validate management accessibility for user and admin sessions.', false, #[\Closure(name: 'App\\Command\\ManagementAccessSmokeCommand')] fn (): \App\Command\ManagementAccessSmokeCommand => ($container->privates['App\\Command\\ManagementAccessSmokeCommand'] ?? $container->load('getManagementAccessSmokeCommandService')));
    }
}
