<?php

namespace Container28xyWKx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getManagementAccessSmokeCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ManagementAccessSmokeCommand' shared autowired service.
     *
     * @return \App\Command\ManagementAccessSmokeCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'ManagementAccessSmokeCommand.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'AnimalManagementService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'WorkerManagementService.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? $container->load('getDoctrine_Dbal_DefaultConnectionService'));

        $container->privates['App\\Command\\ManagementAccessSmokeCommand'] = $instance = new \App\Command\ManagementAccessSmokeCommand(($container->services['kernel'] ?? $container->get('kernel', 1)), ($container->privates['App\\Service\\OracleSqlPlusCrudService'] ?? $container->load('getOracleSqlPlusCrudServiceService')), new \App\Service\AnimalManagementService($a), new \App\Service\WorkerManagementService($a));

        $instance->setName('app:management-access-smoke');
        $instance->setDescription('Validate management accessibility for user and admin sessions.');

        return $instance;
    }
}
