<?php

namespace Container28xyWKx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOracleSessionSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\OracleSessionSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\OracleSessionSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'OracleSessionSubscriber.php';

        return $container->privates['App\\EventSubscriber\\OracleSessionSubscriber'] = new \App\EventSubscriber\OracleSessionSubscriber();
    }
}
