endroid_qr_code:
    default:
         writer: png
    size: 300
    margin: 10
        encoding: 'UTF-8'
        error_correction_level: 'low'
        round_block_size_mode: 'margin'
        validate_result: false
